# ChatGPT. "Python dictionary of territories and their neighboring territories in the RISK board game." OpenAI,
# 23 Feb. 2023, https://openai.com/.

territory_attack_map = {
    'Alaska': ['Northwest Territory', 'Alberta', 'Kamchatka'],
    'Northwest Territory': ['Alaska', 'Greenland', 'Alberta', 'Ontario'],
    'Greenland': ['Northwest Territory', 'Iceland', 'Quebec'],
    'Alberta': ['Alaska', 'Northwest Territory', 'Ontario', 'Western United States'],
    'Ontario': ['Northwest Territory', 'Greenland', 'Quebec', 'Western United States', 'Eastern United States',
                'Alberta'],
    'Quebec': ['Ontario', 'Eastern United States', 'Greenland'],
    'Western United States': ['Alberta', 'Ontario', 'Eastern United States', 'Central America'],
    'Eastern United States': ['Western United States', 'Ontario', 'Quebec', 'Central America'],
    'Central America': ['Western United States', 'Eastern United States', 'Venezuela'],
    'Venezuela': ['Central America', 'Peru', 'Brazil'],
    'Peru': ['Venezuela', 'Brazil', 'Argentina'],
    'Brazil': ['Peru', 'Venezuela', 'Argentina', 'North Africa'],
    'Argentina': ['Peru', 'Brazil'],
    'North Africa': ['Brazil', 'Western Europe', 'Southern Europe', 'Egypt', 'East Africa', 'Congo'],
    'Egypt': ['North Africa', 'Southern Europe', 'Middle East', 'East Africa'],
    'East Africa': ['Madagascar', 'South Africa', 'Congo', 'North Africa', 'Egypt', 'Middle East'],
    'Congo': ['North Africa', 'East Africa', 'South Africa'],
    'South Africa': ['Madagascar', 'East Africa', 'Congo'],
    'Madagascar': ['South Africa', 'East Africa'],
    'Western Europe': ['North Africa', 'Southern Europe', 'Great Britain', 'Northern Europe', 'Southern Europe',
                       'Northern Europe'],
    'Southern Europe': ['Western Europe', 'North Africa', 'Middle East', 'Egypt', 'Northern Europe', 'Ukraine',
                        'Western Europe'],
    'Middle East': ['Southern Europe', 'Egypt', 'East Africa', 'India', 'Afghanistan', 'Ukraine'],
    'Ukraine': ['Northern Europe', 'Southern Europe', 'Middle East', 'Afghanistan', 'Ural', 'Siberia'],
    'Northern Europe': ['Western Europe', 'Southern Europe', 'Ukraine', 'Great Britain', 'Scandinavia'],
    'Great Britain': ['Iceland', 'Scandinavia', 'Northern Europe', 'Western Europe'],
    'Iceland': ['Greenland', 'Great Britain', 'Scandinavia'],
    'Scandinavia': ['Iceland', 'Great Britain', 'Northern Europe', 'Ukraine'],
    'Afghanistan': ['Ukraine', 'Ural', 'China', 'India', 'Middle East'],
    'India': ['Middle East', 'Afghanistan', 'China', 'Siam'],
    'Siam': ['India', 'China', 'Indonesia'],
    'China': ['Siam', 'India', 'Afghanistan', 'Ural', 'Siberia', 'Mongolia'],
    'Mongolia': ['China', 'Siberia', 'Irkutsk', 'Kamchatka', 'Japan'],
    'Japan': ['Mongolia', 'Kamchatka'],
    'Irkutsk': ['Mongolia', 'Siberia', 'Yakutsk', 'Kamchatka', 'Japan'],
    'Yakutsk': ['Siberia', 'Kamchatka', 'Irkutsk'],
    'Kamchatka': ['Yakutsk', 'Alaska', 'Japan', 'Mongolia', 'Irkutsk'],
    'Indonesia': ['Siam', 'Western Australia', 'New Guinea'],
    'New Guinea': ['Indonesia', 'Eastern Australia', 'Western Australia'],
    'Western Australia': ['Indonesia', 'Eastern Australia', 'New Guinea'],
    'Eastern Australia': ['Western Australia', 'New Guinea'],
    'Ural': ['Siberia', 'China', 'Afghanistan', 'Ukraine'],
    'Siberia': ['Ural', 'China', 'Mongolia', 'Irkutsk', 'Yakutsk']
}

risk_cards = [
    ('Alaska', 'Infantry', 2),
    ('Alberta', 'Cavalry', 2),
    ('Argentina', 'Infantry', 2),
    ('Brazil', 'Cavalry', 2),
    ('Central America', 'Infantry', 2),
    ('China', 'Cavalry', 2),
    ('Congo', 'Infantry', 2),
    ('East Africa', 'Infantry', 2),
    ('Eastern Australia', 'Cavalry', 2),
    ('Eastern United States', 'Infantry', 3),
    ('Egypt', 'Infantry', 2),
    ('Great Britain', 'Infantry', 3),
    ('Greenland', 'Infantry', 2),
    ('Iceland', 'Infantry', 1),
    ('India', 'Cavalry', 3),
    ('Indonesia', 'Cavalry', 2),
    ('Irkutsk', 'Cavalry', 2),
    ('Japan', 'Cavalry', 2),
    ('Kamchatka', 'Artillery', 2),
    ('Madagascar', 'Infantry', 1),
    ('Middle East', 'Artillery', 3),
    ('Mongolia', 'Cavalry', 2),
    ('New Guinea', 'Artillery', 1),
    ('North Africa', 'Infantry', 3),
    ('Northern Europe', 'Artillery', 3),
    ('Northwest Territory', 'Infantry', 3),
    ('Ontario', 'Cavalry', 3),
    ('Peru', 'Infantry', 2),
    ('Quebec', 'Infantry', 3),
    ('Scandinavia', 'Infantry', 3),
    ('Siam', 'Cavalry', 2),
    ('Siberia', 'Infantry', 2),
    ('South Africa', 'Cavalry', 2),
    ('Southern Europe', 'Artillery', 3),
    ('Ukraine', 'Artillery', 3),
    ('Ural', 'Cavalry', 2),
    ('Venezuela', 'Cavalry', 2),
    ('Western Australia', 'Artillery', 2),
    ('Western Europe', 'Artillery', 3),
    ('Western United States', 'Artillery', 3),
    ('Yakutsk', 'Cavalry', 2),
    ('Wild Card', 'Wild', 2),
]

